[settings]
resolution = 24
scaling = 1.0
diffusion = 0         # Diffusion constant
dt = 1.0             # Timestep
viscosity = 0.000001  # Viscosity constant

# [[obstacle]]
# position = [4, 4, 4]
# model = "resources/models/cube.obj"

# [[obstacle]]
# position = [12, 11.275, 12]
# model = "resources/models/untitled_textures/untitled_texures.obj"

[[obstacle]]
position = [12, 12, 12]
model = "resources/models/torus.obj"
