[settings]
resolution = 24
scaling = 1.0
diffusion = 0         # Diffusion constant
dt = 1.0             # Timestep
viscosity = 0.000001  # Viscosity constant

insert_position = [12, 12, 1]
insert_velocity = [0, 0, 5]

# [[obstacle]]
# position = [12, 12, 14]
# model = "resources/models/untitled_textures/untitled_texures.obj"
# identifier = "plane"

[[obstacle]]
position = [1,1,1]
model = "resources/models/cube.obj"
identifier = "cube"

# [[obstacle]]
# position = [12, 12, 12]
# model = "resources/models/torus.obj"
# identifier = "torus"
